### ISSUE TITLE
README links to broken link

### ISSUE THREAD

**Issue by nathanhannig** [MarketSquare/robotframework-seleniumscreenshots#19]
The README links to https://datakurre.github.io/robotframework-seleniumscreenshots/ which is a 404 error

**Comment by nathanhannig** [comment]
the correct url is https://marketsquare.github.io/robotframework-seleniumscreenshots/

that document also needs links updated such as https://marketsquare.github.io/robotframework-seleniumscreenshots/keywords.html

**Comment by datakurre** [comment]
@nathanhannig Thanks!
